### PR TITLE
Us03/doing exam

### PR DESCRIPTION
**Pull request by aduongdnai**
Doing exam and Review result use Database
image
Click on "Xem lại bài làm" button
image
image
image
the blue one is user answer, the green one is correct answer, and the red one is incorrect answer

### CODE REVIEW

**Review by QUanlE79 — COMMENTED** [review]
Could you update image sprite for multiple choice answer that will make consistancy with doing exercise

**Comment by aduongdnai** [comment]
> Could you update image sprite for multiple choice answer that will make consistancy with doing exercise

What do you mean

**Comment by aduongdnai** [comment]
> Could you update image sprite for multiple choice answer that will make consistancy with doing exercise

What do you mean? More details, please?

**Review by QUanlE79 — COMMENTED** [review]
image
Like this

**Comment by aduongdnai** [comment]
> image Like this

i have already edited as you said

**Comment by aduongdnai** [comment]
> image Like this

i  edited as you said quan

**Review by QUanlE79 — APPROVED** [review]
LGTM

**Pull request merged**
