### PR TITLE
US02 - interactive book

### PR DESCRIPTION
**Pull request by thaihiepnguyen**
Screenshot 2024-04-18 123817

### CODE REVIEW

**Review by QUanlE79 — CHANGES_REQUESTED** [review]
This feature have to be in the horizontal screen and require drag or have 2 buttons to swap between each pages, not scroll in the vertical screen.

**Comment by thaihiepnguyen** [comment]
Because It's so hard to layout in the horizontal screen. The size of horizontal screen is not enough to display all of content of a page in that book.

**Comment by thaihiepnguyen** [comment]
Let's discuss this at the next meeting.

**Comment by dbchau10** [comment]
The left, right button isnt working

**Review by dbchau10 — CHANGES_REQUESTED** [review]
the left and right button isnt working

**Pull request closed without merging**
